name: Push
run-name: Run checks and everything from ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate compile commands
        run:
          cd ${{ github.workspace }} && make clean && bear -- make -j$(nproc)
      - name: Precommit checks
        uses: pre-commit/action@v3.0.0
      - name: Builds the executable
        run: |
          cd ${{ github.workspace }} && make clean && make -j$(nproc)
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Input tests
        run: |
          cd ${{ github.workspace }} && ./bin/tests-input
